### ISSUE TITLE
Package request: nglview

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/docker-quip-base#7]
https://github.com/arose/nglview

This is a jupyter notebook visualiser for atoms. I'm just playing with it now, seems to be superior to imolecule and chemview, particularly for large systems. There's an ASE interface in latest ASE release: https://wiki.fysik.dtu.dk/ase/ase/visualize/visualize.html#viewer-for-jupyter-notebooks

**Comment by gabor1** [comment]
Adam Fekete was very positive about this one. 

-- Gábor

**Comment by gabor1** [comment]
I managed to get this to work in the docker, by doing the jupyter enable thingy, and restarting the notebook. @tdaff could you please add the required packages to the docker ? we need nglview, and the jupyter enable line (from their readme on their github page)

**Comment by jameskermode** [comment]
I needed to run the following command in docker shell before nglview worked in a notebook:
`jupyter nbextension enable --py widgetsnbextension`
